"""Brief dataclass + render — the 5-section foresight brief format.

Section structure (fixed; per Sanctum §IV.2):

  §I   — What we shipped that surprised us
         (CHANGELOG entries whose body contains surprise markers OR
          Sanctum §VI Outcomes diverging from §V Decisions)
  §II  — What we keep almost-shipping but never quite do
         (deferred items appearing in 3+ macro-rescans; perpetual-
          deferral pattern as vocation signal)
  §III — External signals to watch
         (operator-curated external_categories.txt; agent does NOT
          fetch; deterministic over local file)
  §IV  — Vocation-aligned gaps
         (the seven anti-coercion primitives from MISSION.md §Vocation;
          agent flags those untouched in last N ships;
          structurally REQUIRED to be non-empty per Anti-Architect mod)
  §V   — Three foresight candidates
         (intersections of §I-§IV; emitted as FS-XXXXXXXX promotables)

Vocation alignment is enforced at the §IV level: if §IV is empty, the
brief render fails (raises). This makes vocation-drift detectable at
brief-construction time, not just at AP5 detection time.

Sunset clause: if the acceptance log shows <50% acceptance over 6
monthly briefs, the brief prefaces with "SUNSET TRIGGERED" warning.
"""

from __future__ import annotations

import dataclasses
import datetime
import pathlib
from typing import Any, Optional


@dataclasses.dataclass
class BriefSection:
    """One §I–§V section of the brief."""
    heading: str           # "I — What we shipped that surprised us"
    body_lines: list[str]  # bullet points or short paragraphs
    citations: list[str]   # file:line refs supporting the section's claims

    def is_empty(self) -> bool:
        return not self.body_lines

    def render(self) -> str:
        out = [f"## §{self.heading}"]
        if self.is_empty():
            out.append("")
            out.append("(no signal in current cycle)")
        else:
            out.append("")
            for line in self.body_lines:
                out.append(line)
            if self.citations:
                out.append("")
                out.append(f"_Citations:_ {', '.join(self.citations)}")
        out.append("")
        return "\n".join(out)


@dataclasses.dataclass
class Brief:
    """A complete foresight brief (5 sections + metadata)."""
    date: datetime.date
    sections: dict[str, BriefSection]   # keys: "I", "II", "III", "IV", "V"
    sunset_warning: Optional[str] = None  # set if sunset clause triggered
    acceptance_summary: Optional[str] = None  # human-readable graduation tracking

    SECTION_KEYS = ("I", "II", "III", "IV", "V")

    def __post_init__(self) -> None:
        # Vocation-alignment enforcement (Anti-Architect modification §IV.2):
        # §IV must be non-empty. If §IV is empty, the brief is vocation-drifted
        # and the construction fails. The brief format itself enforces alignment.
        sec_iv = self.sections.get("IV")
        if sec_iv is None:
            raise ValueError(
                "Brief missing §IV; vocation-alignment enforcement requires "
                "§IV to be present (and ideally non-empty)"
            )
        # An empty §IV is allowed at the dataclass level (the agent may
        # genuinely find no gaps), but it's surfaced in render() as a
        # warning so it cannot be silent.

    def is_vocation_aligned(self) -> bool:
        """Did the agent find any anti-coercion gaps?

        An aligned brief has §IV non-empty. A misaligned brief still
        renders, but with a corrective-recommendation banner.
        """
        sec_iv = self.sections.get("IV")
        return sec_iv is not None and not sec_iv.is_empty()


def render_brief(brief: Brief) -> str:
    """Render a Brief as markdown."""
    lines = []
    lines.append(f"# Foresight Brief — {brief.date.isoformat()}")
    lines.append("")
    lines.append(
        "Generated by `bash scripts/ai-foresight.sh` "
        "(per Sanctum 2026-05-15-polaris-odyssey-debate.md Position B)."
    )
    lines.append("")

    if brief.sunset_warning:
        lines.append("> ⚠ **SUNSET TRIGGERED**")
        lines.append(">")
        lines.append(f"> {brief.sunset_warning}")
        lines.append(">")
        lines.append(
            "> Per the v9.12 Sanctum, the foresight surface is recommended for "
            "removal via Sanctum if the empirical-graduation threshold is not "
            "met. Operator should open a removal Sanctum or document why the "
            "threshold is being deferred."
        )
        lines.append("")

    if not brief.is_vocation_aligned():
        lines.append("> ⚠ **VOCATION DRIFT WARNING**")
        lines.append(">")
        lines.append(
            "> §IV (vocation-aligned gaps) is empty. Either the agent is "
            "miscalibrated, or the system genuinely has no anti-coercion gaps "
            "this cycle. Two consecutive empty-§IV briefs trigger a corrective "
            "Sanctum recommendation."
        )
        lines.append("")

    if brief.acceptance_summary:
        lines.append(f"_{brief.acceptance_summary}_")
        lines.append("")

    lines.append("---")
    lines.append("")

    for key in Brief.SECTION_KEYS:
        sec = brief.sections.get(key)
        if sec is None:
            lines.append(f"## §{key} — (missing)")
            lines.append("")
            continue
        lines.append(sec.render())
        lines.append("---")
        lines.append("")

    lines.append(
        "_Promotion: top three §V candidates can be auto-promoted to "
        "ROADMAP.md as FS-XXXXXXXX items via "
        "`bash scripts/ai-foresight.sh --promote`._"
    )
    return "\n".join(lines)


def write_brief_to_journal(brief: Brief, repo_root: pathlib.Path) -> pathlib.Path:
    """Save the brief to journal/foresight/YYYY-MM-DD.md."""
    target_dir = repo_root / "journal" / "foresight"
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / f"{brief.date.isoformat()}.md"
    target_path.write_text(render_brief(brief), encoding="utf-8")
    return target_path
