"""ant_brain_map_freshness — surfaces stale brain-map relative to source.

Consciousness ant. Slice: `meta/brain-map/brain-map.html` vs the
most-recent mtime under tracked source roots.

Local rule: if `brain-map.html` is older than the most-recent
source file by more than `STALE_HOURS` (default 48h), deposit a
`drift` pheromone. The brain map is auto-regenerated by
`scripts/ai-done.sh` check #13; staleness here usually means
ai-done.sh hasn't been run recently — the swarm's self-portrait is
out of date.

G18 (consciousness): reads swarm self-state (the brain-map
artifact's mtime), not runtime pheromones.

Determinism: optional `at` parameter for replay safety. Output
depends on file mtimes only — no wall-clock leakage into intensity.

Authorized by `sanctum/2026-05-13-arc-e-acceleration-consciousness-cohort-e10.md`.
"""

from __future__ import annotations

from datetime import datetime, timezone

from polaris_swarm.base import Ant, AntFinding, KIND_DRIFT


STALE_HOURS = 48.0

SCAN_DIRS = (
    "polaris_web", "polaris_hydra", "polaris_swarm",
    "polaris_sql", "scripts",
)
SCAN_EXTS = {".py", ".sh", ".sql", ".js", ".css", ".html"}

BRAIN_MAP_PARTS = ("meta", "brain-map", "brain-map.html")


def _most_recent_source_mtime(
    root,
) -> datetime | None:
    """Find the latest mtime across SCAN_DIRS × SCAN_EXTS.
    Returns None if no source files exist.

    v9.05 / B1: filters venv/, site-packages/, etc. via
    scan_filters.is_polaris_source — pre-v9.05 the latest mtime
    was usually a pip-touched site-packages file, not Polaris source,
    making the brain-map "stale" detection systematically wrong."""
    from polaris_swarm.scan_filters import is_polaris_source
    latest: float | None = None
    for sd in SCAN_DIRS:
        base = root / sd
        if not base.is_dir():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix not in SCAN_EXTS:
                continue
            if not is_polaris_source(path):
                continue
            try:
                mtime_ts = path.stat().st_mtime
            except OSError:
                continue
            if latest is None or mtime_ts > latest:
                latest = mtime_ts
    if latest is None:
        return None
    return datetime.fromtimestamp(latest, tz=timezone.utc)


class AntBrainMapFreshness(Ant):
    NAME = "ant_brain_map_freshness"
    DESCRIPTION = "Pheromones meta/brain-map/brain-map.html when older than source."

    def __init__(self, root, seed=None, at: datetime | None = None):
        super().__init__(root, seed=seed)
        self.at = at if at is not None else datetime.now(timezone.utc)

    def scan(self) -> list[AntFinding]:
        brain_path = self.root.joinpath(*BRAIN_MAP_PARTS)
        if not brain_path.is_file():
            return [AntFinding(
                node_id="brain_map:freshness",
                intensity=5.0,
                kind=KIND_DRIFT,
                evidence={
                    "message": (
                        f"{'/'.join(BRAIN_MAP_PARTS)} missing — "
                        "no swarm self-portrait exists"
                    ),
                    "fix_hint": (
                        "run scripts/ai-brain-map.sh to generate it"
                    ),
                },
                half_life_hours=72.0,
            )]
        try:
            brain_mtime = datetime.fromtimestamp(
                brain_path.stat().st_mtime, tz=timezone.utc,
            )
        except OSError:
            return []
        latest_source = _most_recent_source_mtime(self.root)
        if latest_source is None:
            return []
        # If brain-map newer than (or same as) every source, fresh.
        if brain_mtime >= latest_source:
            return []
        gap_hours = (latest_source - brain_mtime).total_seconds() / 3600.0
        if gap_hours < STALE_HOURS:
            return []
        intensity = round(min(7.0, 1.0 + gap_hours / 24.0), 3)
        return [AntFinding(
            node_id="brain_map:freshness",
            intensity=intensity,
            kind=KIND_DRIFT,
            evidence={
                "message": (
                    f"brain-map.html is {gap_hours:.1f}h behind the "
                    "most-recent source file"
                ),
                "brain_map_iso": brain_mtime.isoformat(),
                "latest_source_iso": latest_source.isoformat(),
                "gap_hours": round(gap_hours, 3),
                "fix_hint": (
                    "run scripts/ai-done.sh (check #13 regenerates "
                    "the brain map automatically)"
                ),
            },
            half_life_hours=72.0,
        )]
