#!/bin/bash
# =============================================================================
# scripts/ai-foresight.sh — the Polaris Foresight surface (v9.12)
#
# Runs the deterministic ForesightAgent and emits a 5-section brief.
# Saturn-pass cadence (monthly) per meta/cadences.md, operator-installed
# only (no auto-cron).
#
# WHO the foresight surface is lives in polaris_foresight/README.md.
# WHAT the agent says at any moment is generated by polaris_foresight/.
#
# This is the minimum-viable surface from the v9.12 Sanctum
# (polaris-odyssey-debate, Position B). If it earns its right to expand
# via the empirical-graduation rule (50% acceptance over 6 monthly
# briefs), a future Sanctum may extract it into a real subsystem
# (the proposed "Polaris_Odyssey" name held in reserve).
#
# Usage:
#     ai-foresight.sh                    # brief to stdout
#     ai-foresight.sh --save             # also write journal/foresight/YYYY-MM-DD.md
#     ai-foresight.sh --save --promote   # save + auto-promote top-3 §V candidates
#                                        #   to ROADMAP.md (idempotent)
#     ai-foresight.sh --voice            # print polaris_foresight/README.md
#     ai-foresight.sh --top-n N          # change number of candidates promoted (default 3)
# =============================================================================

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

if [ -t 1 ]; then
    BOLD="\033[1m"; G="\033[0;32m"; Y="\033[0;33m"; R="\033[0;31m"
    DIM="\033[2m"; CYAN="\033[0;36m"; GOLD="\033[38;5;220m"
    PURPLE="\033[0;35m"; NC="\033[0m"
else
    BOLD=""; G=""; Y=""; R=""; DIM=""; CYAN=""; GOLD=""; PURPLE=""; NC=""
fi

SAVE=0
PROMOTE=0
TOP_N=3
while [ $# -gt 0 ]; do
    case "$1" in
        --save)       SAVE=1; shift ;;
        --promote)    PROMOTE=1; shift ;;
        --top-n)      TOP_N="$2"; shift 2 ;;
        --voice)      cat "$ROOT/polaris_foresight/README.md"; exit 0 ;;
        --help|-h)    sed -n '2,30p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) shift ;;
    esac
done

# Validate top-n
if ! [[ "$TOP_N" =~ ^[1-9]$|^1[0-9]$|^20$ ]]; then
    echo "Error: --top-n must be 1..20 (got: $TOP_N)" >&2
    exit 1
fi

# Header
printf "${BOLD}${GOLD}%s${NC}\n" "POLARIS FORESIGHT — Saturn-pass brief"
printf "${DIM}%s${NC}\n" "$(date '+%Y-%m-%d %H:%M %Z')"
printf "${DIM}Source: polaris_foresight/ (per Sanctum 2026-05-15-polaris-odyssey-debate.md Position B)${NC}\n"
printf "\n"

cd "$ROOT" || exit 1

# Generate brief via Python entry point
PYTHONPATH="$ROOT" python3 - <<PYEOF
import sys
import pathlib

sys.path.insert(0, "$ROOT")

from polaris_foresight.foresight_agent import ForesightAgent
from polaris_foresight.brief import render_brief, write_brief_to_journal
from polaris_foresight.promotion import (
    parse_brief_for_candidates,
    promote_foresight_candidates,
)

repo_root = pathlib.Path("$ROOT")
agent = ForesightAgent(repo_root=repo_root)
brief = agent.generate()

rendered = render_brief(brief)
print(rendered)

# Update acceptance log with this brief emission (whether saved or not)
agent.update_acceptance_log_after_brief()

if "$SAVE" == "1":
    saved_path = write_brief_to_journal(brief, repo_root)
    print()
    print(f"# Saved to: {saved_path.relative_to(repo_root)}")

if "$PROMOTE" == "1":
    candidates = parse_brief_for_candidates(rendered)
    if not candidates:
        print()
        print("# No candidates parsed from §V; nothing to promote.")
    else:
        result = promote_foresight_candidates(
            candidates,
            roadmap_path=repo_root / "ROADMAP.md",
            top_n=$TOP_N,
        )
        print()
        print(f"# AUTO-PROMOTION: {result.summary_line()}")
        if result.promoted_ids:
            print(f"#   Promoted IDs: {', '.join(result.promoted_ids)}")
            print(f"#   See: ROADMAP.md §\"Foresight candidates (v9.12+)\"")
PYEOF
