#!/bin/bash
# =============================================================================
# scripts/ai-snapshot.sh — single-shot project state dump (v8.6)
#
# Sometimes you need everything-at-once: handing off a session to another
# agent, copying state into a long-context prompt, or producing a report
# for a session retrospective. This script emits a single self-contained
# Markdown document covering the project's full picture.
#
# Sections:
#   1. Identity      — date, git status surrogate (recent files), test counts
#   2. Mission       — C1-C10 status, v1+v2 done-list rollup
#   3. Roadmap       — open ROADMAP items by version
#   4. Active arc    — what the agent should be working on
#   5. Recent decisions — last 10 journal entries (decisions only)
#   6. Substrate     — primitive count from SystemDependency view
#   7. File map      — top-level layout, abbreviated
#
# Designed to fit in ≤ 8000 tokens so it's a usable long-context primer.
#
# Usage:
#     scripts/ai-snapshot.sh                       # to stdout
#     scripts/ai-snapshot.sh > snapshot.md          # to file
# =============================================================================

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
cd "$ROOT"

# Plain output — no color, since this is meant to be piped/captured
sec() { printf "\n## %s\n\n" "$1"; }
sub() { printf "### %s\n\n" "$1"; }

cat <<HDR
# Polaris — project snapshot

Generated by \`scripts/ai-snapshot.sh\` on $(date '+%Y-%m-%d %H:%M %Z')
Host: $(uname -s) $(uname -r)
Repo: $ROOT

This is a self-contained primer. Read it once and you have the full
operational state of Polaris: mission progress, roadmap, and recent
decisions.
HDR

# -----------------------------------------------------------------------------
sec "Mission state (C1-C10)"
# -----------------------------------------------------------------------------
constraint_lines=$("$HERE/ai-status.sh" 2>/dev/null \
    | sed -n '/Hard constraints/,/Mission done-list/p' \
    | grep -E '^\s+[✓!]')
n_ok=$(printf '%s\n' "$constraint_lines" | grep -c '✓' || true)
n_warn=$(printf '%s\n' "$constraint_lines" | grep -c '!' || true)
printf "%s of 10 hard constraints in force.\n\n" "$n_ok"
printf '```\n'
printf '%s\n' "$constraint_lines" | sed 's/^[[:space:]]*//' | head -10
printf '```\n'

# -----------------------------------------------------------------------------
sec "Mission done-list"
# -----------------------------------------------------------------------------
v1_done=$(grep -cE '^[0-9]+\. ✅' MISSION.md | head -1)
# Retired = out-of-scope items kept for audit-of-record (v8.26).
# Match both ✗ (post-v8.26) and ⏸ (pre-v8.26).
v1_def=$(grep -cE  '^[0-9]+\. (✗|⏸)'  MISSION.md | head -1)
v2_done=$(grep -cE 'M2-[0-9]+\. ✅' MISSION.md | head -1)
v2_open=$(grep -cE 'M2-[0-9]+\. ⬜' MISSION.md | head -1)
printf "v1 (closed): **%s ✅**, ✗ %s retired\n" "${v1_done:-0}" "${v1_def:-0}"
printf "v2 (active): **%s ✅**, %s ⬜ open\n\n" "${v2_done:-0}" "${v2_open:-0}"

sub "v2 done-list (active reward function)"
printf '```\n'
grep -E '^M2-[0-9]+\. [✅🟡⬜]' MISSION.md \
    | sed -E 's/^(M2-[0-9]+\. [✅🟡⬜] \*\*[^*]*\*\*).*/\1/'
printf '```\n'

# -----------------------------------------------------------------------------
sec "Roadmap — open items"
# -----------------------------------------------------------------------------
sub "v10 substrate-arc (D)"
printf '```\n'
grep -E '^### R10-' ROADMAP.md | grep -v '✅' | sed 's/^### //'
printf '```\n\n'

sub "v11 open-problems (A)"
printf '```\n'
grep -E '^### R11-' ROADMAP.md | grep -v '✅' | sed 's/^### //'
printf '```\n'

# -----------------------------------------------------------------------------
sec "Top suggested moves"
# -----------------------------------------------------------------------------
printf '```\n'
"$HERE/ai-propose.sh" 3 2>/dev/null \
    | sed -n '/Top.*proposed moves/,/Next steps/p' \
    | grep -E '^[0-9]+\. R|^   risk:|^   mission:' \
    | head -12
printf '```\n'

# -----------------------------------------------------------------------------
sec "Recent decisions (last 10 journal entries)"
# -----------------------------------------------------------------------------
latest_journal=$(ls -1t journal/*.md 2>/dev/null | head -1)
if [ -n "$latest_journal" ]; then
    printf "From \`%s\`:\n\n" "$latest_journal"
    grep -E '^- \*\*decision\*\*' "$latest_journal" 2>/dev/null \
        | tail -10 \
        | sed 's/^/- /'
fi

# -----------------------------------------------------------------------------
sec "Substrate dependencies"
# -----------------------------------------------------------------------------
if command -v psql >/dev/null 2>&1; then
    substrate_summary=$(PGPASSWORD=polaris_dev_password psql -h localhost \
        -U polaris_app -d polaris_test -tA \
        -c "SELECT layer || ': ' || count(*) FROM SystemDependency GROUP BY layer ORDER BY layer;" \
        2>/dev/null)
    if [ -n "$substrate_summary" ]; then
        printf "%s primitives across %s layers (full manifest in \`DEVNOTES/substrate.md\`).\n\n" \
            "$(PGPASSWORD=polaris_dev_password psql -h localhost -U polaris_app \
                -d polaris_test -tA -c 'SELECT count(*) FROM SystemDependency' 2>/dev/null)" \
            "$(printf '%s\n' "$substrate_summary" | wc -l | tr -d ' ')"
        printf '```\n'
        printf '%s\n' "$substrate_summary"
        printf '```\n'
    fi
fi

# -----------------------------------------------------------------------------
sec "Top-level file map"
# -----------------------------------------------------------------------------
printf '```\n'
printf '  Top-level docs (root):\n'
ls -1 *.md 2>/dev/null | sed 's/^/    /'
printf '\n  Reference docs (docs/):\n'
ls -1 docs/*.md 2>/dev/null | sed 's|^docs/|    |'
printf '\n  Source tree:\n'
printf '    polaris_sql/  ($(ls polaris_sql/*.sql 2>/dev/null | wc -l | tr -d " ") SQL files)\n'
printf '    polaris_web/  (Flask app — app.py, security.py, templates/, static/)\n'
printf '    polaris_cli/  (CLI tool)\n'
printf '\n  Scripts (scripts/):\n'
ls -1 scripts/ai-*.sh 2>/dev/null | sed 's|^scripts/|    |'
printf '```\n'

# -----------------------------------------------------------------------------
sec "Test counts"
# -----------------------------------------------------------------------------
printf '```\n'
"$HERE/ai-test-counts.sh" 2>/dev/null | sed -n '/Polaris test/,/^$/p'
printf '```\n'

# -----------------------------------------------------------------------------
sec "Recently modified (last 24h)"
# -----------------------------------------------------------------------------
recent=$(find . -type f \
    \( -name '*.py' -o -name '*.sql' -o -name '*.md' -o -name '*.sh' \
       -o -name '*.html' -o -name '*.js' -o -name '*.css' \) \
    -not -path '*/node_modules/*' \
    -not -path '*/__pycache__/*' \
    -not -path '*/.git/*' \
    -not -path '*/journal/*' \
    -mtime -1 2>/dev/null \
    | sed 's|^\./||' \
    | sort \
    | head -20)
if [ -n "$recent" ]; then
    printf '```\n%s\n```\n' "$recent"
else
    printf "Nothing modified in the last 24 hours.\n"
fi

cat <<FTR

---

*This snapshot was generated by \`scripts/ai-snapshot.sh\`. Re-run any
time the project state has shifted enough that the picture above is
stale. The companion script \`scripts/ai-prime.sh\` emits a shorter
80-line version meant for quick session onboarding.*
FTR
